name: Build-box64

on:
    schedule:
        - cron: '0 1 * * *'
    workflow_dispatch:

jobs:
    compare-upstream-downstream:
        runs-on: ubuntu-24.04-arm
        steps:
            - name: Get Latest Release
              id: upstream
              uses: pozetroninc/github-action-get-latest-release@master
              with:
                owner: ptitSeb
                repo: box64
                excludes: prerelease, draft
            - name: Get Latest Release
              id: downstream
              uses: pozetroninc/github-action-get-latest-release@master
              with:
                repository: ${{github.repository}}
                excludes: prerelease, draft